---
www_prefix: "{{ local_dir }}"
www_virtual_host_dir: "{{ var_dir }}/www"
www_network_virtual_host_dir: "{{ www_virtual_host_dir }}/{{ network_name }}"
www_ca_info_dir: "{{ www_network_virtual_host_dir }}/ca"
www_conf_dir: "{{ local_conf_dir }}/apache24"
www_conf_file: "httpd.conf"
www_conf_path: "{{ www_conf_dir }}/{{ www_conf_file }}"
www_cert_file: "https-cert.pem"
www_cert_path: "{{ ssl_certs_dir }}/{{ www_cert_file }}"
www_key_file: "https-key.pem"
www_key_path: "{{ ssl_keys_dir }}/{{ www_key_file }}"
www_principal: "HTTP/{{ ansible_fqdn }}@{{ kerberos_realm }}"
www_keytab_file: "apache.keytab"
www_keytab_path: "{{ keytabs_dir }}/{{ www_keytab_file }}"