# Network configuration file for "example.com"
---
network_name: "example.com"
kerberos_realm: "EXAMPLE.COM"

ldap_base_dn: "dc=example,dc=com"
ldap_users_dn: "ou=people,{{ ldap_base_dn }}"
ldap_groups_dn: "ou=groups,{{ ldap_base_dn }}"
ldap_hosts_dn: "ou=hosts,{{ ldap_base_dn }}"

ldap_primary_uri: ldaps://ldap.example.com

ldap_alternate_uris:
  - ldaps://ldap2.example.com

tomcat_webapps:
  example:
    group_name: "example"
    kerberos_auth: true
    principal: example/example.example.com@EXAMPLE.COM
    url: ajp://example.example.com:8008
    proxy_fwd_flags: nocanon
    proxy_rev_flags:
