# Network configuration file for "example.com"
---
network_name: "example.com"
kerberos_realm: "EXAMPLE.COM"

ldap_base_dn: "dc=example,dc=com"
ldap_users_dn: "ou=people,{{ ldap_base_dn }}"
ldap_groups_dn: "ou=groups,{{ ldap_base_dn }}"
ldap_hosts_dn: "ou=hosts,{{ ldap_base_dn }}"

ldap_uris:
  - ldaps://ldap.example.com