---
# Basic system directories

conf_dir: "/etc"
local_dir: "/usr/local"
local_conf_dir: "{{ local_dir }}/etc"
var_dir: "/var"
db_dir: "{{ var_dir }}/db"
log_dir: "{{ var_dir }}/log"
run_dir: "{{ var_dir }}/run"
queue_dir: "{{ var_dir }}/spool"
local_var_dir: "{{ local_dir }}/var"
local_lib_dir: "{{ local_dir }}/lib"
local_libexec_dir: "{{ local_dir }}/libexec"
local_bin_dir: "{{ local_dir }}/bin"
local_sbin_dir: "{{ local_dir }}/sbin"
local_share_dir: "{{ local_dir }}/share"

pam_dir: "{{ conf_dir }}/pam.d"
keytabs_dir: "{{ conf_dir }}/keytabs"

# Major system config files

rc_conf: "{{ conf_dir }}/rc.conf"
nsswitch_conf: "{{ conf_dir }}/nsswitch.conf"
mailer_conf: "{{ conf_dir }}/mailer.conf"

# Configurations for creating user accounts

nonexistent_home: "/nonexistent"
nologin_class: "/usr/sbin/nologin"
empty_dir: "{{ var_dir }}/empty"

# System binaries

kinit_bin: "/usr/bin/kinit"
sendmail_bin: "{{ local_sbin_dir }}/sendmail"

# OpenJDK

openjdk_version: 8
openjdk_dir: "{{ local_dir }}/openjdk{{ openjdk_version }}"
openjdk_jre_dir: "{{ openjdk_dir }}/jre"
openjdk_jre_lib_dir: "{{ openjdk_jre_dir }}/lib"
openjdk_jre_security_dir: "{{ openjdk_jre_lib_dir }}/security"
openjdk_cacerts_keystore_file: "cacerts"
openjdk_cacerts_keystore_path: "{{ openjdk_jre_security_dir }}/{{ openjdk_cacerts_keystore_file }}"

# Definition of users and groups

root_user: root
root_group: wheel

mail_group: mail

nslcd_user: nslcd
nslcd_group: nslcd
nslcd_uid: 928
nslcd_gid: 928

slapd_user: ldap
slapd_group: ldap
slapd_uid: 389
slapd_gid: 389

sasl_group: mail

dovecot_group: dovecot
dovecot_user: dovecot
dovecot_gid: 143
dovecot_uid: 143

postfix_group: postfix
postfix_user: postfix
postfix_gid: 125
postfix_uid: 125

dovecot_login_group: dovenull
dovecot_login_user: dovenull
dovecot_login_gid: 143
dovecot_login_uid: 143

maia_group: vscan
maia_user: vscan
maia_gid: 110
maia_uid: 110

clamav_group: clamav
clamav_user: clamav
clamav_gid: 106
clamav_uid: 106

postgres_group: postgres
postgres_user: postgres
postgres_gid: 70
postgres_uid: 70

www_group: www
www_user: www
www_gid: 80
www_uid: 80

tor_group: _tor
tor_user: _tor
tor_gid: 256
tor_uid: 256

privoxy_group: privoxy
privoxy_user: privoxy
privoxy_gid: 201
privoxy_uid: 201

squid_user: squid
squid_group: squid
squid_uid: 100
squid_gid: 100

amavisd_user: "{{ clamav_user }}"
amavisd_group: "{{ clamav_group }}"
amavisd_uid: "{{ clamav_uid }}"
amavisd_gid: "{{ clamav_gid }}"

tomcat_user: "{{ www_user }}"
tomcat_group: "{{ www_group }}"
tomcat_uid: "{{ www_uid }}"
tomcat_gid: "{{ www_gid }}"

postgrey_group: postgrey
postgrey_user: postgrey
postgrey_gid: 225
postgrey_uid: 225

tomcat_version: "8.5"

# Service names

sshd_service: "sshd"
nslcd_service: "nslcd"
kdc_service: "kdc"
saslauthd_service: "saslauthd"
slapd_service: "slapd"
dovecot_service: "dovecot"
postfix_service: "postfix"
postgrey_service: "postgrey"
maiad_service: "maiad"
freshclam_service: "clamav_freshclam"
clamd_service: "clamav_clamd"
amavisd_service: "amavisd"
postgres_service: "postgresql"
www_service: "apache24"
tor_service: "tor"
privoxy_service: "privoxy"
squid_service: "squid"
tomcat_service: "tomcat85"
opendkim_service: "milter-opendkim"
