---
# Basic system directories

conf_dir: "/etc"
local_dir: "/usr/local"
local_conf_dir: "{{ local_dir }}/etc"
var_dir: "/var"
run_dir: "{{ var_dir }}/run"
db_dir: "{{ var_dir }}/db"
queue_dir: "{{ var_dir }}/spool"
local_var_dir: "{{ local_dir }}/var"
local_lib_dir: "{{ local_dir }}/lib"
local_libexec_dir: "{{ local_dir }}/libexec"
local_sbin_dir: "{{ local_dir }}/sbin"

pam_dir: "{{ conf_dir }}/pam.d"
keytabs_dir: "{{ conf_dir }}/keytabs"

# Major system config files

rc_conf: "{{ conf_dir }}/rc.conf"
nsswitch_conf: "{{ conf_dir }}/nsswitch.conf"
mailer_conf: "{{ conf_dir }}/mailer.conf"

# Configurations for creating user accounts

nonexistent_home: "/nonexistent"
nologin_class: "/usr/sbin/nologin"
empty_dir: "{{ var_dir }}/empty"

# System binaries

kinit_bin: "/usr/bin/kinit"
sendmail_bin: "{{ local_sbin_dir }}/sendmail"

# Definition of users and groups

root_user: root
root_group: wheel

nslcd_user: nslcd
nslcd_group: nslcd
nslcd_uid: 928
nslcd_gid: 928

slapd_user: ldap
slapd_group: ldap
slapd_uid: 389
slapd_gid: 389

sasl_group: mail

dovecot_group: dovecot
dovecot_user: dovecot
dovecot_gid: 143
dovecot_uid: 143

postfix_group: postfix
postfix_user: postfix
postfix_gid: 125
postfix_uid: 125

dovecot_login_group: dovenull
dovecot_login_user: dovenull
dovecot_login_gid: 143
dovecot_login_uid: 143

maia_group: vscan
maia_user: vscan

# Service names

sshd_service: "sshd"
nslcd_service: "nslcd"
kdc_service: "kdc"
saslauthd_service: "saslauthd"
slapd_service: "slapd"
dovecot_service: "dovecot"
postfix_service: "postfix"