---
postfix_ldap_cert_file: "{{ ansible_fqdn }}-postfix-ldap-cert.pem"
postfix_ldap_cert_path: "{{ ssl_certs_dir }}/{{ postfix_ldap_cert_file }}"
postfix_ldap_key_file: "{{ ansible_fqdn }}-postfix-ldap-key.pem"
postfix_ldap_key_path: "{{ ssl_keys_dir }}/{{ postfix_ldap_key_file }}"
postfix_mail_cert_path: "{{ ssl_certs_dir }}/smtp-cert.pem"
postfix_mail_key_path: "{{ ssl_keys_dir }}/smtp-key.pem"
postfix_conf_dir: "{{ local_conf_dir }}/postfix"
postfix_daemon_dir: "{{ local_libexec_dir }}/postfix"
postfix_data_dir: "{{ db_dir }}/postfix"
postfix_main_cf_file: "main.cf"
postfix_main_cf_path: "{{ postfix_conf_dir }}/{{ postfix_main_cf_file }}"
postfix_master_cf_file: "master.cf"
postfix_master_cf_path: "{{ postfix_conf_dir }}/{{ postfix_master_cf_file }}"
postfix_ldap_cf_file: "postfix-ldap.cf"
postfix_ldap_cf_path: "{{ postfix_conf_dir }}/{{ postfix_ldap_cf_file }}"
postfix_keytab_file: "postfix.keytab"
postfix_keytab_path: "{{ keytabs_dir }}/{{ postfix_keytab_file }}"
postfix_principal: "postfix/{{ ansible_fqdn }}@{{ kerberos_realm }}"
amavisd_conf_dir: "{{ local_conf_dir }}"
amavisd_conf: "{{ amavisd_conf_dir }}/amavisd.conf"
clamd_conf_dir: "{{ local_conf_dir }}"
clamd_conf: "{{ clamd_conf_dir }}/clamd.conf"