- name: Create dovecot group
  group:
    name: "{{ dovecot_group }}"
    gid: "{{ dovecot_gid }}"
  tags:
    - setup

- name: Create dovecot user
  user:
    name: "{{ dovecot_user }}"
    uid: "{{ dovecot_uid }}"
    group: "{{ dovecot_group }}"
    comment: "Dovecot user"
    home: "{{ empty_dir }}"
    login_class: "daemon"
    shell: "{{ nologin_class }}"
    system: yes
  tags:
    - setup

- name: Create dovenull group
  group:
    name: "{{ dovecot_login_group }}"
    gid: "{{ dovecot_login_gid }}"
  tags:
    - setup

- name: Create dovenull user
  user:
    name: "{{ dovecot_login_user }}"
    uid: "{{ dovecot_login_uid }}"
    group: "{{ dovecot_login_group }}"
    comment: "Dovecot login user"
    home: "{{ empty_dir }}"
    login_class: "daemon"
    shell: "{{ nologin_class }}"
    system: yes
  tags:
    - setup

- name: Install ldap client certificate
  copy:
    src: "{{ control_ssl_client_CA_certs_dir }}/{{ dovecot_ldap_cert_file }}"
    dest: "{{ dovecot_ldap_cert_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - setup
    - ssl
  register: dovecot_ldap_cert

- name: Install ldap client key
  copy:
    src: "{{ control_ssl_client_CA_keys_dir }}/{{ dovecot_ldap_key_file }}"
    dest: "{{ dovecot_ldap_key_path }}"
    owner: "{{ root_user }}"
    group: "{{ dovecot_group }}"
    mode: 0640
  tags:
    - setup
    - ssl
  register: dovecot_ldap_key

- name: Install mail certificate
  copy:
    src: "{{ control_letsencrypt_mail_cert_path }}"
    dest: "{{ dovecot_mail_cert_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - setup
    - ssl
  register: dovecot_mail_cert

- name: Install mail key
  copy:
    src: "{{ control_letsencrypt_mail_key_path }}"
    dest: "{{ dovecot_mail_key_path }}"
    owner: "{{ root_user }}"
    group: "{{ dovecot_group }}"
    mode: 0640
  tags:
    - setup
    - ssl
  register: dovecot_mail_key

- name: Check dovecot keytab
  file:
    path: "{{ dovecot_keytab_path }}"
    owner: "{{ root_user }}"
    group: "{{ dovecot_group }}"
    mode: 0640
  tags:
    - setup

# Set up the dovecot.conf and dovecot-ldap.conf files

- name: Create dovecot-ldap.conf file
  template:
    src: dovecot-ldap.conf.j2
    dest: "{{ dovecot_ldap_conf_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - setup
    - config
  register: dovecot_ldap_conf

- name: Create dovecot.conf file
  template:
    src: dovecot.conf.j2
    dest: "{{ dovecot_conf_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - setup
    - config
  register: dovecot_conf

# Set up a cron job to periodically refresh the dovecot user's
# Kerberos credentials

- name: Add cron job to refresh dovecot user's credentials
  cron:
    name: "Refresh dovecot Kerberos credentials"
    minute: "0"
    hour: "*/6"
    user: "{{ dovecot_user }}"
    job: "{{ kinit_bin }} -k -t {{ dovecot_keytab_path }} {{ dovecot_principal }}"
  tags:
    - setup

# Install a PAM configuration file identical to that of system for IMAP

- name: Install IMAP PAM configuration
  copy:
    src: imap.pam
    dest: "{{ pam_dir }}/imap"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - setup
    - config

# Enable dovecot is enabled in rc.conf and ensure the daemon is running.

- name: Enable dovecot in rc.conf
  lineinfile:
    dest: "{{ rc_conf }}"
    regexp: "^dovecot_enable="
    line: "dovecot_enable=YES"
  tags:
    - setup

- name: Ensure dovecot is running
  service:
    name: "{{ dovecot_service }}"
    state: started

- name: Restart dovecot
  service:
    name: "{{ dovecot_service }}"
    state: restarted
  tags:
    - ssl
    - config
  when: dovecot_ldap_cert.changed or
        dovecot_ldap_key.changed or
        dovecot_mail_cert.changed or
        dovecot_mail_key.changed or
        dovecot_ldap_conf.changed or
        dovecot_conf.changed or
        server_ca_ssl.changed