- name: Install krb5.conf file
  template:
    src: krb5.conf.j2
    dest: "{{ krb5_conf_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - setup
    - config
    - kerberos

- name: Install PAM configurations
  copy:
    src: "{{ item }}.pam"
    dest: "{{ pam_dir }}/{{ item }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  with_items:
    - system
    - other
    - su
  tags:
    - setup
    - config
    - pam
