- name: Create clamav group
  group:
    name: "{{ clamav_group }}"
    gid: "{{ clamav_gid }}"
  tags:
    - setup

- name: Create clamav user
  user:
    name: "{{ clamav_user }}"
    uid: "{{ clamav_uid }}"
    group: "{{ clamav_group }}"
    groups: "{{ mail_group }}"
    comment: "Clamav Antivirus"
    home: "{{ nonexistent_home }}"
    login_class: "daemon"
    shell: "{{ nologin_class }}"
    system: yes
  tags:
    - setup

- name: Enable clamav-freshclam in rc.conf
  lineinfile:
    dest: "{{ rc_conf }}"
    regexp: "^clamav_freshclam_enable="
    line: "clamav_freshclam_enable=YES"
  tags:
    - setup

- name: Enable clamav-clamd in rc.conf
  lineinfile:
    dest: "{{ rc_conf }}"
    regexp: "^clamav_clamd_enable="
    line: "clamav_clamd_enable=YES"
  tags:
    - setup

- name: Ensure clamav-freshclam is running
  service:
    name: "{{ freshclam_service }}"
    state: started

- name: Restart clamav-freshclam
  service:
    name: "{{ freshclam_service }}"
    state: restarted
  tags:
    - ssl
    - config

- name: Ensure clamav-clamd is running
  service:
    name: "{{ clamd_service }}"
    state: started

- name: Restart clamav-clamd
  service:
    name: "{{ clamd_service }}"
    state: restarted
  tags:
    - ssl
    - config
  when: server_ca_ssl.changed
