# Enable amavisd in rc.conf and ensure the daemon is running.

- name: Enable amavisd in rc.conf
  lineinfile:
    dest: "{{ rc_conf }}"
    regexp: "^amavisd_enable="
    line: "amavisd_enable=YES"
  tags:
    - setup

- name: Create amavisd.conf file
  template:
    src: mailer.conf.j2
    dest: "{{ mailer_conf }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - setup
    - config
  register: amavisd_conf

- name: Ensure amavisd is running
  service:
    name: "{{ amavisd_service }}"
    state: started

- name: Restart amavisd
  service:
    name: "{{ amavisd_service }}"
    state: restarted
  tags:
    - ssl
    - config
  when: server_ca_ssl.changed or
        amavisd_conf.changed
