- name: Create base data directory
  file:
    path: "{{ xwiki_data_dir }}"
    state: directory
    owner: "{{ xwiki_user }}"
    group: "{{ xwiki_group }}"
    mode: 0755
  tags:
    - setup

- name: Create specific wikis' data directory
  file:
    path: "{{ xwiki_data_dir }}/{{ item }}"
    state: directory
    owner: "{{ xwiki_user }}"
    group: "{{ xwiki_group }}"
    mode: 0755
  tags:
    - setup
  with_items:
    - "public_wiki"
    - "private_wiki"

- name: Install private wiki properties file
  template:
    src: "xwiki.properties.j2"
    dest: "{{ private_wiki_xwiki_cfg_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - config
    - setup
  vars:
    wiki_name: "private_wiki"

- name: Install public wiki properties file
  template:
    src: "xwiki.properties.j2"
    dest: "{{ public_wiki_xwiki_cfg_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - config
    - setup
  vars:
    wiki_name: "public_wiki"

# Set up the config files

- name: Install private wiki config file
  template:
    src: "xwiki.cfg.j2"
    dest: "{{ private_wiki_xwiki_cfg_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - config
    - setup
  vars:
    validation_key: "{{ private_wiki_validation_key }}"
    encryption_key: "{{ private_wiki_encryption_key }}"
    user_group: "private-wiki-users"
    admin_group: "private-wiki-admin"

- name: Install public wiki config file
  template:
    src: "xwiki.cfg.j2"
    dest: "{{ public_wiki_xwiki_cfg_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - config
    - setup
  vars:
    validation_key: "{{ public_wiki_validation_key }}"
    encryption_key: "{{ public_wiki_encryption_key }}"
    user_group: "public-wiki-users"
    admin_group: "public-wiki-admin"

- name: Install private wiki hibernate config file
  template:
    src: "hibernate.cfg.xml.j2"
    dest: "{{ private_wiki_hibernate_cfg_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - config
    - setup
  vars:
    db_host: "{{ private_wiki_db_host }}"
    db_name: "{{ private_wiki_db_name }}"
    db_username: "{{ private_wiki_db_username }}"
    jaas_appname: "private_wiki"

- name: Install public wiki hibernate config file
  template:
    src: "hibernate.cfg.xml.j2"
    dest: "{{ public_wiki_hibernate_cfg_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - config
    - setup
  vars:
    db_host: "{{ public_wiki_db_host }}"
    db_name: "{{ public_wiki_db_name }}"
    db_username: "{{ public_wiki_db_username }}"
    jaas_appname: "public_wiki"

- name: Copying private wiki cache config
  template:
    src: "cache_config.xml.j2"
    dest: "{{ private_wiki_cache_config_path }}"
  tags:
    - setup
    - config
  vars:
    wiki_name: "private_wiki"

- name: Copying public wiki cache config
  template:
    src: "cache_config.xml.j2"
    dest: "{{ public_wiki_cache_config_path }}"
  tags:
    - setup
    - config
  vars:
    wiki_name: "public_wiki"
