# Ensure that tor user and group exist

- name: Create tor group
  group:
    name: "{{ tor_group }}"
    gid: "{{ tor_gid }}"
  tags:
    - setup

- name: Create tor user
  user:
    name: "{{ tor_user }}"
    group: "{{ tor_group }}"
    comment: "Tor anonymizing router"
    uid: "{{ tor_uid }}"
    home: "{{ tor_data_dir }}"
    shell: "{{ nologin_class }}"
    system: yes
  tags:
    - setup

# Set up the torrc files

- name: Create torrc file
  template:
    src: torrc.j2
    dest: "{{ torrc_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - setup
    - config
  register: torrc

# Enable tor in rc.conf and ensure the daemon is running.

- name: Enable tor in rc.conf
  lineinfile:
    dest: "{{ rc_conf }}"
    regexp: "^tor_enable="
    line: "tor_enable=YES"
  tags:
    - setup

- name: Ensure tor is running
  service:
    name: "{{ tor_service }}"
    state: started

- name: Restart tor
  service:
    name: "{{ tor_service }}"
    state: restarted
  tags:
    - config
  when: torrc.changed
