- name: Install sshd_config
  copy:
    src: sshd_config
    dest: "{{ sshd_config_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - config
    - setup
  register: sshd_config

- name: Ensure sshd is running
  service:
    name: "{{ sshd_service }}"
    state: started

- name: Restart sshd
  service:
    name: "{{ sshd_service }}"
    state: restarted
  when: sshd_config.changed